#!/bin/sh

sudo apt-get install --no-install-recommends --assume-yes \
	alsa-utils \
	xorg \
	i3 \
	gnome-themes-standard \
	adwaita-icon-theme \
	chromium-browser

cat > "${HOME}/.xinitrc" << 'EOF'
#!/bin/sh

if [ -x /usr/bin/VBoxClient ]; then
  for process in ${HOME}/.vboxclient-*.pid; do
    [ -w "${process}" ] || rm -f "${process}"
  done
  /usr/bin/VBoxClient --clipboard || true
  /usr/bin/VBoxClient --checkhostversion || true
  /usr/bin/VBoxClient --display || true
  /usr/bin/VBoxClient --seamless || true
  /usr/bin/VBoxClient --draganddrop || true
fi

if [ -x /usr/bin/amixer ]; then
  /usr/bin/amixer set Master unmute
  /usr/bin/amixer set Master 100%
  /usr/bin/amixer set PCM unmute
  /usr/bin/amixer set PCM 100%
fi

if [ -x /usr/bin/xsetroot ]; then
  /usr/bin/xsetroot -solid '#AF5FAF'
fi

if [ -x /usr/bin/setxkbmap ]; then
  /usr/bin/setxkbmap -layout us -option caps:escape
fi

exec i3
EOF

cat > "${HOME}/.gtkrc-2.0" << 'EOF'
gtk-theme-name="Adwaita"
gtk-icon-theme-name="Adwaita"
gtk-font-name="Sans 10"
gtk-cursor-theme-name="Adwaita"
gtk-cursor-theme-size=0
gtk-toolbar-style=GTK_TOOLBAR_BOTH_HORIZ
gtk-toolbar-icon-size=GTK_ICON_SIZE_BUTTON
gtk-button-images=1
gtk-menu-images=1
gtk-enable-event-sounds=1
gtk-enable-input-feedback-sounds=1
gtk-xft-antialias=1
gtk-xft-hinting=1
gtk-xft-hintstyle="hintfull"
gtk-xft-rgba="rgb"
EOF

install --directory "${XDG_CONFIG_HOME:-${HOME}/.config}/gtk-3.0"
cat > "${XDG_CONFIG_HOME:-${HOME}/.config}/gtk-3.0/settings.ini" << 'EOF'
[Settings]
gtk-application-prefer-dark-theme=1
gtk-theme-name=Adwaita
gtk-icon-theme-name=Adwaita
gtk-font-name=Sans 10
gtk-cursor-theme-name=Adwaita
gtk-cursor-theme-size=0
gtk-toolbar-style=GTK_TOOLBAR_BOTH_HORIZ
gtk-toolbar-icon-size=GTK_ICON_SIZE_BUTTON
gtk-button-images=1
gtk-menu-images=1
gtk-enable-event-sounds=1
gtk-enable-input-feedback-sounds=1
gtk-xft-antialias=1
gtk-xft-hinting=1
gtk-xft-hintstyle=hintfull
gtk-xft-rgba=rgb
EOF

install --directory "${XDG_CONFIG_HOME:-${HOME}/.config}/i3"
cat > "${XDG_CONFIG_HOME:-${HOME}/.config}/i3/config" << 'EOF'
# i3 config file (v4)

font pango:monospace 8
floating_modifier Mod1
new_window pixel 3

bindsym Mod1+Shift+q kill
bindsym Mod1+f fullscreen toggle
bindsym Mod1+Shift+space floating toggle

bindsym Mod1+j focus up
bindsym Mod1+k focus down
bindsym Mod1+h focus left
bindsym Mod1+l focus right

bindsym Mod1+Up focus up
bindsym Mod1+Down focus down
bindsym Mod1+Left focus left
bindsym Mod1+Right focus right

bindsym Mod1+Shift+j move up
bindsym Mod1+Shift+k move down
bindsym Mod1+Shift+h move left
bindsym Mod1+Shift+l move right

bindsym Mod1+Shift+Up move up
bindsym Mod1+Shift+Down move down
bindsym Mod1+Shift+Left move left
bindsym Mod1+Shift+Right move right

bindsym Mod1+g split h
bindsym Mod1+v split v

bindsym Mod1+s layout stacking
bindsym Mod1+w layout tabbed
bindsym Mod1+e layout toggle split

bindsym Mod1+a focus parent
bindsym Mod1+space focus mode_toggle

mode "resize" {
	bindsym j resize shrink height 1 px or 1 ppt
	bindsym k resize grow height 1 px or 1 ppt
	bindsym h resize shrink width 1 px or 1 ppt
	bindsym l resize grow width 1 px or 1 ppt

	bindsym Up resize shrink height 1 px or 1 ppt
	bindsym Down resize grow height 1 px or 1 ppt
	bindsym Left resize shrink width 1 px or 1 ppt
	bindsym Right resize grow width 1 px or 1 ppt

	bindsym Escape mode "default"
}
bindsym Mod1+r mode "resize"

bindsym Mod1+Shift+c reload
bindsym Mod1+Shift+r restart

bindsym Mod1+Return exec "i3-sensible-terminal"
bindsym Mod1+0 exec "chromium-browser"
bindsym Mod1+9 exec "xrandr --output VGA-1 --auto"
bindsym Mod1+Shift+e exec "i3-nagbar -t warning -m 'Exit?' -b 'Yes' 'i3-msg exit'"

bindsym Mod1+1 workspace 1
bindsym Mod1+2 workspace 2
bindsym Mod1+3 workspace 3
bindsym Mod1+4 workspace 4

bindsym Mod1+Shift+1 move container to workspace 1
bindsym Mod1+Shift+2 move container to workspace 2
bindsym Mod1+Shift+3 move container to workspace 3
bindsym Mod1+Shift+4 move container to workspace 4

bar {
	mode hide
	hidden_state hide
	modifier Mod1
}
EOF

